---
title: "About This Website"
---

**About Me:** 
I have lived in New Hampshire my whole life and I can't imagine living anywhere else. The changing seasons and the ability to go to the ocean and mountains in one day is what New England is all about. Although New Hampshire will always be my home I love to travel. 

**Education:** 
I got my B.S. in Marine, Estuarine, and Freshwater Biology from the University of New Hampshire in 2023.
Currently I am in the Marine Biology Masters Program at the University of New Hampshire. My focus for my Masters degree is on Eastern oysters and their behavioral responses to different interactions with European green crabs. 

**Hobbies:** 
I love to be out in nature. Whether it be land or water it doesn't matter to me. When I was young I practically lived in the lake snorkeling around until dusk watching the fish swim around and feed off of the lake floor. I also loved to walk through the woods because on every walk I would encounter something new. The best experience I had in the woods was seeing a bull moose walking away from me towards the swamp that was nearby. I also love to go hiking with my dogs there are so many fun and challenging trails to hike in New Hampshire. While out in the wilderness I love to take pictures! Photography is a passion of mine and I feel that nature creates the most beautiful images.  

```{r, echo=FALSE}
paths <- c("IMG_1.jpg","IMG_2.jpg","Snapseed 3.jpg","IMG_4.jpg", "IMG_5.jpg","IMG_6.jpg","IMG_7.jpg", "IMG_8.jpg","IMG_9.jpg","IMG_10.jpg","IMG_14.jpg","IMG_15.jpg","IMG_16.jpg","IMG_17.jpg","IMG_18.jpg","IMG_19.jpg", "IMG_20.jpg","IMG_21.jpg","IMG_22.jpg","IMG_23.jpg","IMG_24.jpg", "IMG_25.jpg","IMG_26.jpg","IMG_28.jpg")
library(pixture)
pixgallery(paths)
```